export const regions = {
  NSW: [
    'Capital Region',
    'Central Coast',
    'Central West',
    'Coffs Harbour - Grafton',
    'Far West And Orana',
    'Hunter Valley Exc Newcastle',
    'Illawarra',
    'Mid North Coast',
    'Murray',
    'Newcastle And Lake Macquarie',
    'New England And North West',
    'Richmond - Tweed',
    'Riverina',
    'Southern Highlands And Shoalhaven',
    'Sydney - Baulkham Hills And Hawkesbury',
    'Sydney - Blacktown',
    'Sydney - City And Inner South',
    'Sydney - Eastern Suburbs',
    'Sydney - Inner South West',
    'Sydney - Inner West',
    'Sydney - Northern Beaches',
    'Sydney - North Sydney And Hornsby',
    'Sydney - Outer South West',
    'Sydney - Outer West And Blue Mountains',
    'Sydney - Parramatta',
    'Sydney - Ryde',
    'Sydney - South West',
    'Sydney - Sutherland'
  ],
  QLD: [
    'Brisbane Inner City',
    'Sunshine Coast',
    'Central Queensland',
    'Toowoomba',
    'Townsville',
    'Ipswich',
    'Cairns',
    'Wide Bay',
    'Gold Coast',
    'Brisbane - North',
    'Brisbane - South',
    'Brisbane - West',
    'Brisbane - East',
    'Darling Downs - Maranoa',
    'Logan - Beaudesert',
    'Mackay - Isaac - Whitsunday',
    'Moreton Bay - North',
    'Moreton Bay - South',
    'Queensland - Outback'
  ],
  VIC: [
    'Ballarat',
    'Bendigo',
    'Geelong',
    'Hume',
    'Shepparton',
    'Mornington Peninsula',
    'North West',
    'Melbourne - West',
    'Latrobe - Gippsland',
    'Melbourne - Inner',
    'Melbourne - Inner East',
    'Melbourne - Inner South',
    'Melbourne - North East',
    'Melbourne - North West',
    'Melbourne - Outer East',
    'Melbourne - South East',
    'Warrnambool And South West'
  ]
};

export const option = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
];

export const options = [
  'Group',
  'Online service',
  'Telehealth',
  'We come to you',
  'You come to us'
];
export const options1 = [
  'Early Childhood (0-7 years)',
  'Children (8-16 years)',
  'Young people (17-21 years)',
  'Adults (22-59 years)',
  'Mature Age (60+ years)'
];

export const languages = [
  { value: 'Arabic', label: 'Arabic' },
  { value: 'Assyrian', label: 'Assyrian' },
  { value: 'Bengali', label: 'Bengali' },
  { value: 'Burmese', label: 'Burmese' },
  { value: 'Cantonese', label: 'Cantonese' },
  { value: 'Croatian', label: 'Croatian' },
  { value: 'Dari', label: 'Dari' },
  { value: 'Dzongkha', label: 'Dzongkha' },
  { value: 'English', label: 'English' },
  { value: 'EnglishGB', label: 'English-GB' },
  { value: 'EnglishUS', label: 'English-US' },
  { value: 'Fijian', label: 'Fijian' },
  { value: 'French', label: 'French' },
  { value: 'Fulu', label: 'Fulu' },
  { value: 'German', label: 'German' },
  { value: 'Greek', label: 'Greek' },
  { value: 'Gujarati', label: 'Gujarati' },
  { value: 'Hazaraghi', label: 'Hazaraghi' },
  { value: 'Hebrew', label: 'Hebrew' },
  { value: 'Hindi', label: 'Hindi' },
  { value: 'Igbo', label: 'Igbo' },
  { value: 'Indigenous - Warlpiri', label: 'Indigenous - Warlpiri' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Kashmiri', label: 'Kashmiri' },
  { value: 'Korean', label: 'Korean' },
  { value: 'Lao', label: 'Lao' },
  { value: 'Malay', label: 'Malay' },
  { value: 'Malayalam', label: 'Malayalam' },
  { value: 'Mandarin', label: 'Mandarin' },
  { value: 'Marathi', label: 'Marathi' },
  { value: 'Nepalese/Nepali', label: 'Nepalese/Nepali' },
  { value: 'Persian/Farsi', label: 'Persian/Farsi' },
  { value: 'Polish', label: 'Polish' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Punjabi', label: 'Punjabi' },
  { value: 'Rohingya', label: 'Rohingya' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Serbian', label: 'Serbian' },
  { value: 'Sindhi', label: 'Sindhi' },
  { value: 'Sinhalese/Tamil', label: 'Sinhalese/Tamil' },
  { value: 'Somali', label: 'Somali' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'Swahili', label: 'Swahili' },
  { value: 'Tagalog', label: 'Tagalog' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Urdu', label: 'Urdu' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Yoruba', label: 'Yoruba' }
];

export const services = [
  { value: 1, label: 'Cleaning' },
  { value: 2, label: 'Day Center' },
  { value: 3, label: 'Gardening' },
  { value: 4, label: 'Housing' },
  { value: 5, label: 'Interpreters' },
  { value: 6, label: 'Meals' },
  { value: 7, label: 'Social Support' },
  { value: 8, label: 'Educational Support' },
  { value: 9, label: 'Employment Services' },
  { value: 10, label: 'SLES and DES' },
  { value: 11, label: 'Car Modification' },
  { value: 12, label: 'Consumables' },
  { value: 13, label: 'equipment' },
  { value: 14, label: 'Home Modifications and Maintenance' },
  { value: 15, label: 'Software and Apps' },
  { value: 16, label: 'Advocacy and Peer Support' },
  { value: 17, label: 'Plan Management' },
  { value: 18, label: 'Psychosocial Recovery Coaching' },
  { value: 19, label: 'Specialist Support Coordination' },
  { value: 20, label: 'Support Coordination' },
  { value: 21, label: 'Acupuncture' },
  { value: 22, label: 'Chiropractor' },
  { value: 23, label: 'Transport' },
  { value: 24, label: 'Driving' },
  { value: 25, label: 'Nursing Services' },
  { value: 26, label: 'Other' }
];
