// languageToCountryCode.ts
export const languageToCountryCode: Record<string, string> = {
  Arabic: "SA",
  Bengali: "BD",
  Burmese: "MM",
  Cantonese: "HK",
  Croatian: "HR",
  Dari: "AF",
  Dzongkha: "BT",
  English: "AU", // or "GB"
  EnglishGB: "GB", // or "GB"
  EnglishUS: "US", // or "GB"
  Fijian: "FJ",
  French: "FR",
  Fulu: "CD", // Assuming Congo
  German: "DE",
  Greek: "GR",
  Gujarati: "IN",
  Hazaraghi: "AF",
  Hebrew: "IL",
  Hindi: "IN",
  Igbo: "NG",
  "Indigenous - Warlpiri": "AU",
  Indonesian: "ID",
  Italian: "IT",
  Japanese: "JP",
  Kashmiri: "IN",
  Korean: "KR",
  Lao: "LA",
  Malay: "MY",
  Malayalam: "IN",
  Mandarin: "CN",
  Marathi: "IN",
  "Nepalese/Nepali": "NP",
  "Persian/Farsi": "IR",
  Polish: "PL",
  Portuguese: "PT",
  Punjabi: "PK",
  Rohingya: "MM",
  Russian: "RU",
  Serbian: "RS",
  Sindhi: "PK",
  "Sinhalese/Tamil": "LK",
  Somali: "SO",
  Spanish: "ES",
  Swahili: "KE",
  Tagalog: "PH",
  Thai: "TH",
  Turkish: "TR",
  Urdu: "PK",
  Vietnamese: "VN",
  Yoruba: "NG"
};
